env:
  node: true
  es6: true
  mocha: true
  es2020: true

plugins:
  - haraka

extends:
  - eslint:recommended
  - plugin:haraka/recommended

root: true

rules:
  indent: [ error, 2, { SwitchCase: 1 } ]

globals:
  OK: true
  CONT: true
  DENY: true
  DENYSOFT: true
  DENYDISCONNECT: true
  DENYSOFTDISCONNECT: true
