#!/usr/bin/env node
'use strict'
try {
    var reporter = require('nodeunit').reporters.default;
}
catch (e) {
    console.log(`
Error: ${e.message}

Cannot find nodeunit. Did you run 'npm install'?
`)
    process.exit()
}

process.chdir(__dirname);

reporter.run([ 'test' ], undefined, (err) => {
    process.exit(((err) ? 1 : 0));
});
