name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  # coverage:
  #   uses: haraka/.github/.github/workflows/coverage.yml@master
  #   secrets: inherit

  ubuntu:
    needs: [lint]
    uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    needs: [lint]
    uses: haraka/.github/.github/workflows/windows.yml@master
